version: "3.8"
services:
  backend:
    build: ./backend
    container_name: fastapi-backend-dev
    volumes:
      - ./backend:/app
      - ./backend/uploads:/app/uploads
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: ./frontend
    container_name: react-frontend-dev
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    depends_on:
      - backend
    command: pnpm run dev --host